// Arquivo: src/modules/prestadores/constants/filterConstants.js
// Constantes e listas padronizadas para filtros da Rede de Prestadores (Guia Médico / Busca Avançada)

export const PRODUTOS_LIST = [
  { id: '', label: 'Todos os Produtos' },
  { id: 'premium-sp', label: 'Premium São Paulo' },
  { id: 'premium-dourados', label: 'Premium Dourados' },
  { id: 'premium-cg', label: 'Premium Campo Grande' },
  { id: 'exclusivo-cm', label: 'Exclusivo Centro Médico Prudente' }
]

export const ESPECIALIDADES_LIST = [
  { code: '036000', label: 'ACUPUNTURA' },
  { code: '039000', label: 'ALERGIA E IMUNOLOGIA' },
  { code: '108000', label: 'ANALISES CLINICAS' },
  { code: '056000,085000', label: 'ANATOMIA PATOLÓGICA E CITOPATOLOGIA' },
  { code: '058000,109000,110000', label: 'ANESTESIOLOGIA' },
  { code: '041000,111000', label: 'ANGIOLOGIA' },
  { code: '005000', label: 'BIOLOGO' },
  { code: '044000', label: 'CANCEROLOGIA CLÍNICA (ONCOLOGIA CLÍNICA)' },
  { code: '045000', label: 'CANCEROLOGIA PEDIÁTRICA (ONCOLOGIA PEDIÁTRICA)' },
  { code: '043000', label: 'CARDIOLOGIA' },
  { code: '116000', label: 'CARDIOLOGIA PEDIÁTRICA' },
  { code: '068000', label: 'CIRURGIA CARDIOVASCULAR' },
  { code: '084000', label: 'CIRURGIA DA MÃO' },
  { code: '069000', label: 'CIRURGIA DE CABEÇA E PESCOÇO' },
  { code: '070000', label: 'CIRURGIA DO APARELHO DIGESTIVO' },
  { code: '071000', label: 'CIRURGIA GERAL' },
  { code: '083000', label: 'CIRURGIA ONCOLÓGICA' },
  { code: '072000', label: 'CIRURGIA PEDIÁTRICA' },
  { code: '073000', label: 'CIRURGIA PLÁSTICA' },
  { code: '074000', label: 'CIRURGIA TORÁCICA' },
  { code: '067000', label: 'CIRURGIA VASCULAR' },
  { code: '022000', label: 'CIRURGIAO DENTISTA - TRAUMATOLOGISTA BUCOMAXILOFAC' },
  { code: '001000', label: 'CLÍNICO GERAL' },
  { code: '050000', label: 'DERMATOLOGIA' },
  { code: '059000', label: 'ENDOCRINOLOGIA E METABOLOGIA' },
  { code: '086000', label: 'ENDOSCOPIA' },
  { code: '060000', label: 'FISIATRIA' },
  { code: '004000', label: 'FISICO MEDICO' },
  { code: '030000', label: 'FISIOTERAPIA GERAL' },
  { code: '032000', label: 'FONOAUDIOLOGIA' },
  { code: '032001', label: 'FONOAUDIOLOGIA - EXAMES' },
  { code: '120000', label: 'FORNECEDOR' },
  { code: '061000', label: 'GASTROENTEROLOGIA' },
  { code: '002000,063000', label: 'GENÉTICA MÉDICA' },
  { code: '064000', label: 'GERIATRIA' },
  { code: '075000', label: 'GINECOLOGIA E OBSTETRÍCIA' },
  { code: '065000', label: 'HEMATOLOGIA E HEMOTERAPIA' },
  { code: '105000', label: 'HEMODINÂMICA E CARDIOLOGIA INTERVENCIONISTA' },
  { code: '092000', label: 'HEMOTERAPIA' },
  { code: '121000', label: 'HEPATOLOGIA' },
  { code: '066000', label: 'HOMEOPATIA' },
  { code: '035000', label: 'INFECTOLOGIA' },
  { code: '125000', label: 'INTERVENCIONISTA DE DOR' },
  { code: '076000', label: 'MASTOLOGIA' },
  { code: '048000,054000', label: 'MEDICINA DE FAMÍLIA E COMUNIDADE' },
  { code: '055000', label: 'MEDICINA DE TRÁFEGO' },
  { code: '053000', label: 'MEDICINA DO TRABALHO' },
  { code: '057000', label: 'MEDICINA INTENSIVA' },
  { code: '087000', label: 'MEDICINA NUCLEAR' },
  { code: '062000', label: 'MEDICO GENERALISTA' },
  { code: '093000', label: 'MEDICO HIPERBARISTA' },
  { code: '037000', label: 'MEDICO LEGISTA' },
  { code: '052000', label: 'MEDICO SANITARISTA' },
  { code: '038000', label: 'NEFROLOGIA' },
  { code: '077000', label: 'NEUROCIRURGIA' },
  { code: '094000', label: 'NEUROFISIOLOGIA' },
  { code: '040000', label: 'NEUROLOGIA' },
  { code: '097000', label: 'NEUROPSICOLOGIA' },
  { code: '118000', label: 'NEUROPSICOPEDAGOGIA' },
  { code: '031000', label: 'NUTRICIONISTA' },
  { code: '042000', label: 'NUTROLOGIA' },
  { code: '078000', label: 'OFTALMOLOGIA' },
  { code: '079000', label: 'ORTOPEDIA E TRAUMATOLOGIA' },
  { code: '079001', label: 'ORTOPEDIA E TRAUMATOLOGIA - QUADRIL E JOELHO' },
  { code: '034000', label: 'ORTOPEDISTA' },
  { code: '080000', label: 'OTORRINOLARINGOLOGIA' },
  { code: '089000', label: 'PATOLOGIA' },
  { code: '091000', label: 'PATOLOGIA CLÍNICA / MEDICINA LABORATORIAL' },
  { code: '126000', label: 'PEDAGOGIA' },
  { code: '046000', label: 'PEDIATRIA' },
  { code: '003000', label: 'PESQUISADOR EM BIOLOGIA DE MICROORGANISMOS E PARAS' },
  { code: '047000', label: 'PNEUMOLOGIA' },
  { code: '081000', label: 'PROCTOLOGIA' },
  { code: '098000', label: 'PSICANALISTA' },
  { code: '096000', label: 'PSICOLOGIA' },
  { code: '096001', label: 'PSICOLOGIA - ATENDIMENTO INFANTO JUVENIL' },
  { code: '119000', label: 'PSICOMOTRICISTA' },
  { code: '095000', label: 'PSICOPEDAGOGIA' },
  { code: '049000', label: 'PSIQUIATRIA' },
  { code: '088000', label: 'RADIOLOGIA E DIAGNÓSTICO POR IMAGEM' },
  { code: '122000', label: 'RADIOLOGISTA INTERVENCIONISTA' },
  { code: '090000', label: 'RADIOTERAPIA' },
  { code: '051000', label: 'REUMATOLOGIA' },
  { code: '033000', label: 'TERAPIA OCUPACIONAL' },
  { code: '082000', label: 'UROLOGIA' }
]

export const TIPOS_PRESTADOR_LIST = [
  { code: 'ANE', label: 'ANESTESISTA' },
  { code: 'CDI', label: 'CENTRO DE DIAGNOSTICOS' },
  { code: 'CLI', label: 'CLINICA' },
  { code: 'DEN', label: 'DENTISTAS' },
  { code: 'FON', label: 'FONOAUDIOLOGO' },
  { code: 'HOS', label: 'HOSPITAL' },
  { code: 'HOD', label: 'HOSPITAL DIA' },
  { code: 'HOM', label: 'HOSPITAL MATERNIDADE' },
  { code: 'INT', label: 'INSTRUMENTADOR' },
  { code: 'LAB', label: 'LABORATORIO' },
  { code: 'MED', label: 'MEDICO' },
  { code: 'NUT', label: 'NUTRICIONISTA' },
  { code: 'PFN', label: 'PESSOA FISICA - NAO MEDICO' },
  { code: 'EVE', label: 'PRESTADOR EVENTUAL' },
  { code: 'OUT', label: 'PROFISSIONAL DE SAUDE' },
  { code: 'PSI', label: 'PSICOLOGO' },
  { code: 'PSM', label: 'PSICOMOTRICISTA' },
  { code: 'REM', label: 'REMOCOES DE PACIENTES' },
  { code: 'TRP', label: 'TERAPEUTA OCUPACIONAL' },
  { code: 'TES', label: 'TESTE' }
]

export const PLANOS_LIST = [
  { code: '1212', label: 'EXCLUSIVO ADESAO 30%' },
  { code: '8248', label: 'EXCLUSIVO ADESÃO III' },
  { code: '2196', label: 'EXCLUSIVO EMPRESARIAL' },
  { code: '0240', label: 'EXCLUSIVO EMPRESARIAL III' },
  { code: '4192', label: 'EXCLUSIVO INDIVIDUAL 30%' },
  { code: '7240', label: 'EXCLUSIVO INDIVIDUAL III' },
  { code: '4999', label: 'PLANO BASICO' },
  { code: '9111', label: 'PLANO EMPRESARIAL COLETIVO POR ADESAO 30%' },
  { code: '2999', label: 'PLANO EMPRESARIAL NÃO REGULAMENTADO' },
  { code: '1999', label: 'PLANO NÃO REGULAMENTADO INDIVIDUAL OURO' },
  { code: '6208', label: 'PLANO PREMIUM I SP INDIVIDUAL BRONZE' },
  { code: '3109', label: 'PLANO SP BRONZE INDIVIDUAL 30%' },
  { code: '8145', label: 'PLANO SP COLETIVO EMPRESARIAL BRONZE 30%' },
  { code: '7991', label: 'PLANO SP COLETIVO EMPRESARIAL I' },
  { code: '5141', label: 'PLANO SP COLETIVO POR ADESAO BRONZE 20%' },
  { code: '2991', label: 'PLANO SP COLETIVO POR ADESAO IV' },
  { code: '4112', label: 'PLANO SP INDIVIDUAL OU FAMILIAR I' },
  { code: '6993', label: 'PLANO SP INDIVIDUAL OU FAMILIAR I - BRONZE' },
  { code: '5200', label: 'PREMIUM I SP INDIVIDUAL OURO' },
  { code: '2202', label: 'PREMIUM ADESAO OURO' },
  { code: '3228', label: 'PREMIUM EMPRESARIAL ODONTO' },
  { code: '3201', label: 'PREMIUM I SP ADESAO' },
  { code: '0206', label: 'PREMIUM I SP EMPRE OURO 20%' },
  { code: '9202', label: 'PREMIUM I SP EMPRESARIAL BRONZE' },
  { code: '5241', label: 'PREMIUM II DRD MS ADESAO BRONZE' },
  { code: '1249', label: 'PREMIUM II DRD MS EMPRESARIAL BRONZE' },
  { code: '4235', label: 'PREMIUM II MS ADESÃO BRON 30%' },
  { code: '7230', label: 'PREMIUM II MS EMPRESARIAL BRONZE' },
  { code: '1204', label: 'PREMIUM II SP ADESAO BRONZE' },
  { code: '8204', label: 'PREMIUM II SP EMPRESARIAL BRONZE' },
  { code: '7206', label: 'PREMIUM II SP INDIVIDUAL BRONZE' },
  { code: '3245', label: 'PREMIUM III DRD MS ADESAO APTO' },
  { code: '7248', label: 'PREMIUM III DRD MS ADESAO BRONZE' },
  { code: '6240', label: 'PREMIUM III DRD MS EMPRESARIAL BRONZE' },
  { code: '4243', label: 'PREMIUM III DRD MS EMPRESARIAL OURO' },
  { code: '8238', label: 'PREMIUM III MS ADESÃO BRONZE' },
  { code: '2239', label: 'PREMIUM III MS ADESÃO OURO' },
  { code: '6231', label: 'PREMIUM III MS EMPRESARIAL BRONZE' },
  { code: '1231', label: 'PREMIUM III MS EMPRESARIAL OURO' },
  { code: '1224', label: 'PREMIUM III SP ADESAO BRONZE' },
  { code: '0226', label: 'PREMIUM III SP EMPRESARIAL BRONZE' },
  { code: '9211', label: 'PREMIUM III SP INDIVIDUAL BRONZE' },
  { code: '2247', label: 'PREMIUM IV DRD MS ADESÃO BRONZE' },
  { code: '8246', label: 'PREMIUM IV DRD MS EMPRESARIAL BRONZE' },
  { code: '0232', label: 'PREMIUM IV MS ADESAO BRONZE' },
  { code: '5233', label: 'PREMIUM IV MS EMPRESARIAL BRONZE' },
  { code: '5243', label: 'PREMIUM SP ADESÃO BRONZE IV' },
  { code: '9246', label: 'PREMIUM SP EMPRESARIAL BRONZE IV' },
  { code: '6241', label: 'PREMIUM SP IV INDIVIDUAL BRONZE' },
  { code: '3194', label: 'SMART' },
  { code: '1198', label: 'SMART EMPRESARIAL' },
  { code: '5191', label: 'SMART HOSPITALAR' }
]

export const SMART_ESPECIALIDADES_DESTAQUE = [
  'CARDIOLOGIA',
  'CLÍNICO GERAL',
  'DERMATOLOGIA',
  'GINECOLOGIA E OBSTETRÍCIA',
  'OFTALMOLOGIA',
  'ORTOPEDIA E TRAUMATOLOGIA',
  'PEDIATRIA',
  'PSIQUIATRIA',
  'ENDOCRINOLOGIA E METABOLOGIA',
  'GASTROENTEROLOGIA',
  'NEUROLOGIA',
  'UROLOGIA'
]

export const SMART_TIPOS_DESTAQUE = [
  'MED',
  'CLI',
  'HOS',
  'HOD',
  'LAB',
  'CDI',
  'DEN',
  'PSI',
  'NUT',
  'TRP'
]
